pub const REQUEST_ID_NOT_FOUND: felt252 = 'REQUEST_ID_NOT_FOUND';
pub const LENGTH_MISMATCH: felt252 = 'LENGTH_MISMATCH';
pub const NOT_LOANABLE: felt252 = 'NOT_LOANABLE';
pub const CANNOT_COLLATERALIZE: felt252 = 'CANNOT_COLLATERALIZE';
pub const TRANSFER_FAILED: felt252 = 'TRANSFER_FAILED';
pub const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';
