pub const REQUEST_ID_NOT_FOUND: felt252 = 'REQUEST_ID_NOT_FOUND';
pub const LENGTH_MISMATCH: felt252 = 'LENGTH_MISMATCH';
pub const NOT_LOANABLE_TOKEN: felt252 = 'NOT_LOANABLE_TOKEN';
pub const CANNOT_COLLATERALIZE: felt252 = 'CANNOT_COLLATERALIZE';
pub const TRANSFER_FAILED: felt252 = 'TRANSFER_FAILED';
pub const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';

pub const INVALID_REQUEST_ID: felt252 = 'INVALID_REQUEST_ID';
pub const INSUFFICIENT_COLLATERAL: felt252 = 'INSUFFICIENT_COLLATERAL';

pub const REQUEST_ALREADY_SERVICED: felt252 = 'REQUEST_ALREADY_SERVICED';
pub const CANNOT_SERVICE_OWN_REQUEST: felt252 = 'CANNOT_SERVICE_OWN_REQUEST';
